### ISSUE TITLE
Submit article to Water Research

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#30]
The final step to upload the article to _Water Research_ will have a number of components and steps:

  - [ ] @tomschenkjr will create a release on this repository that attaches the separate materials needed for submission (we don't just upload the final PDF, has to be organized a specific way)
    - [ ] Attach a title page #26 
    - [ ] Attach a "manuscript file"
    - [ ] Attach the "highlights" document #17 
  - [ ] In a separate email, we need to get the addresses for the recommended referees #16 
  - [ ] @nicklucius will be the corresponding author, so he will need to [create an account on Elsevier](https://ees.elsevier.com/wr/). Follow the instructions and use the documents in the aforementioned release as part of the process.

These steps should only occur after #23 is completed.

**Comment by tomschenkjr** [comment]
@nicklucius - before next Monday (1/29), complete the Elsevier task.

**Comment by nicklucius** [comment]
I successfully created an Elsevier account.
